<?xml version="1.1" encoding="UTF-8" ?>
<!DOCTYPE sla-profile [

<!ELEMENT sla-profile (description?, sla-threshold*)>
<!ATTLIST sla-profile
    uid CDATA #REQUIRED
    uniqueKey CDATA #REQUIRED>

<!ELEMENT description (#PCDATA)>
	
<!ELEMENT sla-threshold ((threshold-condition )*)>
<!ATTLIST sla-threshold
	uid CDATA #REQUIRED
	percent CDATA #IMPLIED
	identifier CDATA #REQUIRED
	enabled CDATA #REQUIRED
	family CDATA #REQUIRED>

<!ELEMENT threshold-condition (#PCDATA)>
<!ATTLIST threshold-condition
    severity CDATA #REQUIRED
    durationKind CDATA #REQUIRED
    durationNumber CDATA #REQUIRED
    operator CDATA #REQUIRED
    valueMin CDATA #REQUIRED
    valueMax CDATA #REQUIRED>

]>
<sla-profile name="SLA_RealBrowser" uid="df8a8db4-140b-4e8b-9eab-3f9df312bc39">
<description/>
<sla-threshold enabled="false" family="PER_RUN" identifier="AVERAGE_REQUEST_RESPONSE_TIME" percent="1" uid="158e64ca-7f20-4eb1-9a5e-49c71bed9e87"/>
<sla-threshold enabled="false" family="PER_RUN" identifier="AVERAGE_PAGE_RESPONSE_TIME" percent="1" uid="517b87cb-995b-4fcf-81c8-b78746a861b7"/>
<sla-threshold enabled="false" family="PER_RUN" identifier="AVERAGE_CONTAINER_RESPONSE_TIME" percent="1" uid="ad192094-4690-4fb3-91f0-d8e85c33c783"/>
<sla-threshold enabled="false" family="PER_RUN" identifier="PERCENTILE_CONTAINER_RESPONSE_TIME" percent="1" uid="480da5b2-8519-4334-b10f-cb996efb81c3"/>
<sla-threshold enabled="false" family="PER_RUN" identifier="AVERAGE_HITS_PER_SECOND" percent="1" uid="cb589b83-f935-487b-9211-c422c1d0e9c1"/>
<sla-threshold enabled="false" family="PER_RUN" identifier="AVERAGE_THROUGHPUT_PER_SECOND" percent="1" uid="57785302-a8b3-4b66-95e0-f012d2c3f2ea"/>
<sla-threshold enabled="false" family="PER_RUN" identifier="TOTAL_ERRORS" percent="1" uid="6a98ba35-dd92-47cc-91fc-6669fd094d1a"/>
<sla-threshold enabled="false" family="PER_RUN" identifier="TOTAL_HITS" percent="1" uid="19f86329-8c29-40fe-9dbc-36d0c00fa039"/>
<sla-threshold enabled="false" family="PER_RUN" identifier="TOTAL_THROUGHPUT" percent="1" uid="3ea267b4-93eb-4d2b-a204-973a4f042fe4"/>
<sla-threshold enabled="false" family="PER_RUN" identifier="ERROR_PERCENTILE" percent="1" uid="355dc808-b783-4429-9558-378ab01616c9"/>
<sla-threshold enabled="true" family="PER_TIME_INTERVAL" identifier="AVERAGE_RESPONSE_TIME" percent="1" uid="9f9bf920-a9f2-4392-8062-cc6735f30c32">
<threshold-condition durationKind="NB_OF_TIMES" durationNumber="1" operator="GREATER_THAN" severity="HIGH" valueMax="Infinity" valueMin="6.0"/>
<threshold-condition durationKind="NB_OF_TIMES" durationNumber="1" operator="GREATER_THAN" severity="LOW" valueMax="Infinity" valueMin="3.0"/>
</sla-threshold>
<sla-threshold enabled="true" family="PER_TIME_INTERVAL" identifier="AVERAGE_HITS_PER_SECOND" percent="1" uid="2933a60e-9595-4aaa-a5a9-a4d5f1e23efb">
<threshold-condition durationKind="NB_OF_TIMES" durationNumber="1" operator="LESS_THAN" severity="HIGH" valueMax="Infinity" valueMin="4.0"/>
<threshold-condition durationKind="NB_OF_TIMES" durationNumber="1" operator="LESS_THAN" severity="LOW" valueMax="Infinity" valueMin="8.0"/>
</sla-threshold>
<sla-threshold enabled="true" family="PER_TIME_INTERVAL" identifier="AVERAGE_THROUGHPUT_PER_SECOND" percent="1" uid="6a22d15e-6849-446b-88f4-b7b635952ddd">
<threshold-condition durationKind="NB_OF_TIMES" durationNumber="1" operator="LESS_THAN" severity="LOW" valueMax="Infinity" valueMin="0.0"/>
</sla-threshold>
<sla-threshold enabled="true" family="PER_TIME_INTERVAL" identifier="ERRORS_PER_SECOND" percent="1" uid="c395bd43-3ae4-49ba-a4dd-96bf310abf45"/>
<sla-threshold enabled="true" family="PER_TIME_INTERVAL" identifier="ERROR_PERCENTILE" percent="1" uid="2f1b4ebd-7b33-4a40-b3cd-6ce1d692e4ac">
<threshold-condition durationKind="NB_OF_TIMES" durationNumber="1" operator="GREATER_THAN" severity="HIGH" valueMax="Infinity" valueMin="10.0"/>
<threshold-condition durationKind="NB_OF_TIMES" durationNumber="1" operator="GREATER_THAN" severity="LOW" valueMax="Infinity" valueMin="5.0"/>
</sla-threshold>
</sla-profile>
